#makes a release with unity
name: Make Build

on:
  schedule:
    - cron: '59 6 * * 2' #runs at 11:59 on Monday (PDT -> UTC)
  repository_dispatch:
    types: build
permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    env:
      TARGET_PLATFORM: StandaloneWindows64
      SVN_USERNAME: ${{ secrets.svn_username }}
      SVN_PASSWORD: ${{ secrets.svn_password }}

    steps:
    #DO NOT USE actions/checkout! 
    #check out or update svn
    - name: checkout-svn
      env:
        SVN_URL: ${{ secrets.svn_url }}
      run: |
        If ( !(Test-Path -Path svn-repo ) )
        { 
          Write-Host ">> svn-repo was not found. Checking out new copy."
          New-Item -Path ".\svn-repo" -ItemType "Directory"    
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
          cd svn-repo
        } 
        Else {
          Write-Host ">> svn-repo was found. Updating to head revision, if necessary."
          cd svn-repo
          svn update --username $env:SVN_USERNAME --password $env:SVN_PASSWORD
          Write-Host ">> Update successful. Resolving any conflicts."
          svn resolve --accept theirs-full --username $env:SVN_USERNAME --password $env:SVN_PASSWORD 
        }
        Write-Host ">> runner's copy of svn files is now up-to-date."

        "BUILD_NAME=r$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append
        cd .. 

    #set up build variables
    - name: setup-build
      run: |
        cd svn-repo
        New-Item -Path "$env:BUILD_NAME" -ItemType "Directory"
        "BUILD_PATH=$(Resolve-Path -Path $env:BUILD_NAME)" | Out-File -FilePath $env:GITHUB_ENV -Append
        cd ..

    #build the project from the command line; unity is installed on self-hosted runner
    - name: make-build
      env:
        UNITY_PATH: ${{ secrets.unity_path }}
      run: |
        Write-Host ">> Building project."
        dir 
        Start-Process -FilePath $env:UNITY_PATH -ArgumentList "-batchMode","-executeMethod","Builder.BuildProject","-projectPath","svn-repo","outputPath","$env:BUILD_PATH","-buildTarget","Windows"
        Write-Host ">> Build complete."

        cd $env:BUILD_NAME 
        dir
        cd ..

    #upload builds to svn build folder
    - name: upload-build-to-svn
      env: 
        SVN_BUILD: ${{ secrets.SVN_BUILD }}
      run: |
        Write-Host ">> Uploading new build"
        Write-Host ">> Checking out svn-builds"
        New-Item -Path ".\svn-builds" -ItemType "Directory"    
        svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_BUILDS svn-builds --quiet

        Write-Host ">> Moving new build to svn-builds."
        Move-Item -Path "$env:BUILD_PATH" -Destination svn-builds 
        cd svn-builds
        svn commit --username $env:SVN_USERNAME --password $env:SVN_PASSWORD -m "Automated build"
        cd ..

        Remove-Item svn-builds