#makes a release with unity
name: Make Build

on:
  #could also be every time there's a push, if allowed? doesn't have to be time-restricted
  schedule:
    - cron: '59 23 * * 4' #runs at 11:59 on Thursday

env:
  BUILD_NAME: Basil and the Isles of Spice

#TODO: run tests and generate a spreadsheet of passing/failing tests -- but don't stop build
#TODO: log svn versions, git shas between previous and current release and include in build notes
#TODO: compile commit messages to make build notes
jobs:
  build:
    runs-on: windows-latest #possible issue with OS?
    steps:
    - name: make-build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        targetPlatform: Universal Windows Platform
        unityVersion: 2021.3.1 #update if incorrect/changes
    
    - name: upload-build
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build
        