#makes a release with unity
name: Make Build

on:
  schedule:
    - cron: '59 6 * * 2' #runs at 11:59 on Monday (PDT -> UTC)
  repository_dispatch:
    types: build
permissions:
  contents: write

jobs:
  pull-svn:
    uses: ./.github/workflows/pull_svn.yaml
    secrets: inherit
    permissions: 
      contents: write
  build:
    runs-on: self-hosted
    env:
      BUILD_NAME: Basil and the Isles of Spice
      TARGET_PLATFORM: StandaloneWindows64
    steps:
    - uses: actions/checkout@v3
    
    - name: dir-check-1
      run: |
        dir 
        cd svn-repo
        dir
        cd ..

    - name: make-build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        targetPlatform: ${{ env.TARGET_PLATFORM }}
        unityVersion: 2021.3.1f1 
        projectPath: svn-repo
        allowDirtyBuild: true       

    - name: dir-check-2
      run: |
        dir 
        cd build
        dir
        cd ${{env.TARGET_PLATFORM}}
        dir

    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BUILD_NAME }}
        path: build/${{ env.TARGET_PLATFORM }}

    #push changes to github
    #- name: push-build
    #  run: |
    #    git config user.name 'Automated Build'
    #    git config user.email ${{ secrets.UNITY_EMAIL }}
    #    git add build
    #    git commit -m 'Automated Build | ${{ env.BUILD_NAME }}'
    #    git push