#makes a release with unity
name: Make Build

on:
  schedule:
    - cron: '59 23 * * 1' #runs at 11:59 on Thursday
  repository_dispatch:
    types: build
  push:
    branches:
      - "*"

env:
  BUILD_NAME: Basil and the Isles of Spice

#TODO: run tests and generate a spreadsheet of passing/failing tests -- but don't stop build
#TODO: log svn versions, git shas between previous and current release and include in build notes
#TODO: compile commit messages to make build notes
#TODO: NEED DIFFERENT NAMES FOR DIFFERENT BUILDS
jobs:
  build:
    runs-on: windows-latest #possible issue with OS?
    steps:
    - name: checkout-svn
        run: svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
        env:
          SVN_USERNAME: ${{ secrets.svn_username }}
          SVN_PASSWORD: ${{ secrets.svn_password }}
          SVN_URL: ${{ secrets.svn_url }}
    #svn info -r HEAD
    #- name: get-version
    #    run: svn info -r HEAD
        
    - name: make-build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        targetPlatform: Universal Windows Platform
        unityVersion: 2021.3.1 #update if incorrect/changes
        projectPath: trunk/TestProject3D
    
    - name: upload-build
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build
        