#makes a release with unity
name: Make Build

on:
  schedule:
    - cron: '59 23 * * 1' #runs at 11:59 on Monday
  repository_dispatch:
    types: build
permissions:
  contents: write

jobs:
  pull-svn:
    uses: ./.github/workflows/pull_svn.yaml
    secrets: inherit
    permissions: 
      contents: write
  build:
    runs-on: windows-2019 #possible issue with OS?
    env:
      BUILD_NAME: Basil and the Isles of Spice
      TARGET_PLATFORM: StandaloneWindows64
    steps:
    - uses: actions/checkout@v3
    
    - name: make_build_name
      run: |
        cd svn-repo
        "BUILD_NAME=${{ env.BUILD_NAME }} r$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append
        cd ..
      env:
        SVN_USERNAME: ${{ secrets.svn_username }}
        SVN_PASSWORD: ${{ secrets.svn_password }}
      shell: pwsh

    #TODO -- caching --> https://game.ci/docs/github/builder/#caching
    #how can we version the library while keeping it unversioned in svn?
      #...hooks?

    - name: make-build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        targetPlatform: ${{ env.TARGET_PLATFORM }}
        unityVersion: 2021.3.1f1 
        projectPath: svn-repo
        allowDirtyBuild: true        

    #push changes to github
    - name: push-build
      run: |
        git config user.name '$(git log -n 1 --pretty=format:%an)'
        git config user.email '$(git log -n 1 --pretty=format:%ae)'
        git add .
        git commit -m 'Automated Build | $env:BUILD_NAME'
        git push