#updates git repo's versions of svn repo files
name: Pull SVN

on:
  repository_dispatch:
    types: pull-svn

env:
  SVN_USERNAME: ${{ secrets.svn_username }}
  SVN_PASSWORD: ${{ secrets.svn_password }}
  SVN_URL: ${{ secrets.svn_url }}

jobs:
  pull-svn-files:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-git
      uses: actions/checkout@v3

    #check out or update svn
    - name: checkout-svn
      run: chmod +x .github/scripts/update-git-svn.sh
      shell: bash

    #TODO -- add version for the revision to add to the commit message
    #push changes to github
    - name: push-changes
      run: |
        git add .
        git commit -m "Update from commit"
        git push