#updates git repo's versions of svn repo files
name: Pull SVN

on:
  repository_dispatch:
    types: pull-svn
permissions:
  contents: write

env:
  need_update: 'true'

jobs:
  pull-svn-files:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-git
      uses: actions/checkout@v3

    #check out or update svn
    #TODO -- not sure if conflicts will actually get resolved -- only time will tell i guess?
    - name: checkout-svn
      run: |
        if [ ! -d svn-repo ];
        then
          echo ">> svn-repo not found. Checking out new copy."
          svn checkout --username $SVN_USERNAME --password $SVN_PASSWORD $SVN_URL svn-repo
        else
          echo ">> svn-repo found. Checking if update is necessary."
          
          working_revision=$(svn info --show-item revision)
          head_revision=$(svn info --revision HEAD --show-item revision)
          echo 'Working revision is $working_revision. Head revision is $head_revision.'
          
          if [ working_revision == head_revision ];
          then
            echo ">> Update is not necessary."
            need_update='false'
            exit
          else 
            echo ">> Update is necessary."
          fi

          cd svn-repo
          svn update --username $SVN_USERNAME --password $SVN_PASSWORD 
          echo ">> Update successful. Resolving any conflicts."
          svn resolve --accept theirs-full
          cd ..
        fi
        echo ">> git repo's copy of svn files is now up-to-date."
      shell: bash
      env:
        SVN_USERNAME: ${{ secrets.svn_username }}
        SVN_PASSWORD: ${{ secrets.svn_password }}
        SVN_URL: ${{ secrets.svn_url }}

    #TODO -- add version for the revision to add to the commit message
    #push changes to github
    - name: push-changes
      if: ${{ env.need_update }} == 'true'
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "Update from commit"
        git push