#updates git repo's versions of svn repo files
name: Pull SVN

on:
  repository_dispatch:
    types: pull-svn
  workflow_call:
permissions:
  contents: write

jobs:
  pull-svn-files:
    env:
      SVN_USERNAME: ${{ secrets.svn_username }}
      SVN_PASSWORD: ${{ secrets.svn_password }}
      SVN_URL: ${{ secrets.svn_url }}
      CHECK_UPDATE: true
      UPDATED: true
    runs-on: windows-latest
    steps:
    - name: checkout-git
      uses: actions/checkout@v3

    #check out or update svn
    #TODO -- not sure if conflicts will actually get resolved -- only time will tell i guess?
    - name: check-if-checkout-needed
      run: |
        if [ ! -d svn-repo ];
        then
          echo ">> svn-repo not found. Checking out new copy."
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
          echo "CHECK_UPDATE=false" | Out-File -FilePath $env:GITHUB_ENV
          echo "UPDATED=true" | Out-File -FilePath $env:GITHUB_ENV
        fi
      shell: bash
    
    #check version to see if checkout is needed
    - name: get-working-and-head-revisions
      if: ${{ env.CHECK_UPDATE == 'true' }}
      run: |
        cd svn-repo
        echo "SVN_WORKING_REVISION=$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV
        echo "SVN_HEAD_REVISION=$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV
      shell: bash

    - name: update-if-needed
      if: ${{ env.CHECK_UPDATE == 'true' }} 
      run: |
        cd svn-repo
        echo ">> Working revision is ${{ env.SVN_WORKING_REVISION }}"
        echo ">> Head revision is ${{ env.SVN_HEAD_REVISION}}"
        if [ ${{ env.SVN_WORKING_REVISION }} == ${{ env.SVN_HEAD_REVISION }} ];
        then
          echo ">> Update is not necessary."
          echo "UPDATED=false" | Out-File -FilePath $env:GITHUB_ENV
          exit
        else
          echo ">> Update is necessary."
          
          #make tmp folder
          cd .svn
          if [ ! -d svn-repo ];
          then 
            mkdir tmp
          fi 
          cd ..

          svn update --username $env:SVN_USERNAME --password $env:SVN_PASSWORD 
          echo ">> Update successful. Resolving any conflicts."
          svn resolve --accept theirs-full --username $env:SVN_USERNAME --password $env:SVN_PASSWORD 
          echo "UPDATED=true" | Out-File -FilePath $env:GITHUB_ENV
          cd ..
        fi
        echo ">> git repo's copy of svn files is now up-to-date."
      shell: bash
      
    #push changes to github
    - name: push-changes
      if: ${{ env.UPDATED == 'true' }}
      run: |
        git config user.name '$(git log -n 1 --pretty=format:%an)'
        git config user.email '$(git log -n 1 --pretty=format:%ae)'
        git add .
        git commit -m 'Updating svn to r.$HEAD_REVISION'
        git push
      shell: bash