#updates git repo's versions of svn repo files
name: Pull SVN
run-name: Pull from SVN 

on:
  repository_dispatch:
    types: pull-svn
  workflow_call:
permissions:
  contents: write

jobs:
  pull-svn-files:
    env:
      SVN_USERNAME: ${{ secrets.svn_username }}
      SVN_PASSWORD: ${{ secrets.svn_password }}
      SVN_URL: ${{ secrets.svn_url }}
      UPDATED: false
    runs-on: self-hosted
    steps:
    - name: checkout-git
      uses: actions/checkout@v3

    #check out or update svn
    - name: check-if-checkout-needed
      run: |
        If ( !(Test-Path -Path svn-repo ) )
        { 
          New-Item -Path ".\svn-repo" -ItemType "Directory"    
          Write-Host ">> svn-repo was not found. Checking out new copy."
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
        } 
        Else {
          Write-Host ">> svn-repo was found. Updating to head revision, if necessary."
          cd svn-repo
          svn update --username $env:SVN_USERNAME --password $env:SVN_PASSWORD Get-Location
          Write-Host ">> Update successful. Resolving any conflicts."
          svn resolve --accept theirs-full --username $env:SVN_USERNAME --password $env:SVN_PASSWORD 
          cd ..
        }
        Write-Host ">> git repo's copy of svn files is now up-to-date."