#updates git repo's versions of svn repo files
name: Pull SVN
run-name: Pull from SVN 

on:
  repository_dispatch:
    types: pull-svn
  workflow_call:
    inputs:
      revision:
        required: false
        type: string
permissions:
  contents: write

#TODO -- watch for failure and run cleanup 

jobs:
  pull-svn-files:
    env:
      SVN_USERNAME: ${{ secrets.svn_username }}
      SVN_PASSWORD: ${{ secrets.svn_password }}
      SVN_URL: ${{ secrets.svn_url }}
      TARGET_REVISION: "_"
    runs-on: self-hosted
    steps:
    #DO NOT CHECKOUT GIT
    #determine which variable to use
    - name: set-revision
      run: |
        if ( "${{ inputs.revision }}" -eq "" )
        {
          #no input specified; get the head revision
          "TARGET_REVISION=$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append
        }
        else
        {
          #revision specified from workflow call; pass input along
          "TARGET_REVISION=${{ inputs.revision }}" | Out-File -FilePath $env:GITHUB_ENV -Append
        }

    - name: checkout-update-svn
      env:
        SVN_URL: ${{ secrets.svn_url }}
      run: |
        if ( !(Test-Path -Path svn-repo ) )
        { 
          Write-Host ">> svn-repo was not found. Checking out new copy."
          New-Item -Path ".\svn-repo" -ItemType "Directory"    
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL --revision $env:TARGET_REVISION svn-repo 
          cd svn-repo
        } 
        else 
        {
          Write-Host ">> svn-repo was found. Updating to head revision, if necessary."
          cd svn-repo
          svn update --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision $env:TARGET_REVISION
          Write-Host ">> Update successful. Resolving any conflicts."
          svn resolve --accept theirs-full --username $env:SVN_USERNAME --password $env:SVN_PASSWORD 
        }
        Write-Host ">> runner's copy of svn files is now up-to-date."

        cd .. 