#updates git repo's versions of svn repo files
name: Pull SVN
run-name: Pull from SVN 

on:
  repository_dispatch:
    types: pull-svn
  workflow_call:
permissions:
  contents: write

jobs:
  pull-svn-files:
    env:
      SVN_USERNAME: ${{ secrets.svn_username }}
      SVN_PASSWORD: ${{ secrets.svn_password }}
      SVN_URL: ${{ secrets.svn_url }}
    runs-on: self-hosted
    steps:
    #DO NOT CHECK OUT GIT
    #check out or update svn
    - name: checkout-svn
      env:
        SVN_URL: ${{ secrets.svn_url }}
      run: |
        If ( !(Test-Path -Path svn-repo ) )
        { 
          Write-Host ">> svn-repo was not found. Checking out new copy."
          New-Item -Path ".\svn-repo" -ItemType "Directory"    
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
          cd svn-repo
        } 
        Else {
          Write-Host ">> svn-repo was found. Updating to head revision, if necessary."
          cd svn-repo
          svn update --username $env:SVN_USERNAME --password $env:SVN_PASSWORD
          Write-Host ">> Update successful. Resolving any conflicts."
          svn resolve --accept theirs-full --username $env:SVN_USERNAME --password $env:SVN_PASSWORD 
        }
        Write-Host ">> runner's copy of svn files is now up-to-date."

        "BUILD_NAME=BATIOSr$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append
        cd .. 