name: Run tests
permissions:
  contents: write
on: 
  repository_dispatch:
    types: 'end2end'

#TODO - get which assemblies to run from payload, or wherever else it would be if possible

jobs:
  pull-svn:
    uses: ./.github/workflows/pull-svn.yaml
    secrets: inherit
    permissions: 
      contents: write
  run_tests:
    runs-on: self-hosted
    steps:
      #DO NOT CHECK OUT GIT      
      - name: get-head-revision
        run: |
          "BUILD_NAME=BATIOSr$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append

      #run tests through testing pipeline
      - name: run-tests
        run: |
          Write-Host ">> Running tests."
          Start-Process (Join-Path -Path (Get-Location) -ChildPath "\svn-repo\Hooks\run_tests.exe") 
          
        env:
          SVN_USERNAME: ${{ secrets.svn_username }}
          SVN_PASSWORD: ${{ secrets.svn_password }}

      #create the log and then push change to commit
      - name: push-log
        run: |
          cd test_logs
          echo "${{ env.TEST_OUTPUT }}" > test_log.txt
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "Automated test results for Revision ${{ env.SVN_HEAD_REVISION }}"
          git push
        shell: bash 

