name: Run tests
permissions:
  contents: write
on: 
  repository_dispatch:
    types: 'test'

#TODO - get which assemblies to run from payload, or wherever else it would be if possible

jobs:
  pull-svn:
    uses: ./.github/workflows/pull-svn.yaml
    secrets: inherit
    permissions: 
      contents: write
  run_tests:
    needs: pull-svn
    runs-on: self-hosted
    env:
      SVN_USERNAME: ${{ secrets.svn_username }}
      SVN_PASSWORD: ${{ secrets.svn_password }}
    steps:
      #DO NOT CHECK OUT GIT      
      - name: init-test-variables
        run: |
          #clean up the directory in case a previous run failed
          If ( Test-Path -Path svn-tests )
          {
            Remove-Item -Path ".\svn-tests" -Recurse -Force
          }

          cd svn-repo
          "HEAD_REVISION=$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append
          "BUILD_NAME=BATIOSr$(svn info --username $env:SVN_USERNAME --password $env:SVN_PASSWORD --revision HEAD --show-item revision)" | Out-File -FilePath $env:GITHUB_ENV -Append
          "RUN_TESTS_PATH=$(Join-Path -Path (Get-Location) -ChildPath "Hooks\run_tests.exe")" | Out-File -FilePath $env:GITHUB_ENV -Append
          cd ..
        
      #run tests through testing pipeline
      - name: run-tests
        run: |
          "TEST_LOG_NAME=results_$env:HEAD_REVISION.xlsx" | Out-File -FilePath $env:GITHUB_ENV -Append
          &"$env:RUN_TESTS_PATH" --head_rev $env:HEAD_REVISION
          cd svn-repo
          cd hooks
          cd test_artifacts
          dir
          cd ..
          cd ..
          cd ..
          cd ..

      #rename the test log and move it into the test log folder
      - name: commit-test-log
        run: |
          Write-Host ">> Checking out svn-tests"
          New-Item -Path ".\svn-tests" -ItemType "Directory"    
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_TEST svn-tests --quiet
          
          Write-Host ">> Moving new test log to svn-tests."
          Rename-Item -Path ".\svn-repo\Hooks\test_artifacts\results_$env:HEAD_REVISION.xlsx" -NewName "$env:TEST_LOG_NAME"
          Move-Item -Path ".\svn-repo\Hooks\test_artifacts\$env:TEST_LOG_NAME" -Destination ".\svn-tests"

          Write-Host ">> Committing new test log to svn."
          cd svn-tests
          svn add $env:TEST_LOG_NAME --username $env:SVN_USERNAME --password $env:SVN_PASSWORD
          svn commit --username $env:SVN_USERNAME --password $env:SVN_PASSWORD -m "Automated test results"
          cd ..                  

          Write-Host ">> Cleaning up."
          Remove-Item -Path ".\svn-tests" -Recurse -Force
          Write-Host ">> Done!."
        env:
          SVN_TEST: ${{ secrets.svn_test }}


