name: Run end to end tests
run-name: Run more expensive tests that would take too long to run before commits
permissions:
  contents: write
on: [push]
  #repository_dispatch:
  #  types: end2end

env:
  TEST_RESULTS: "joe mama"

jobs:
  run_tests:
    runs-on:  windows-latest
    steps:
      - name: checkout-svn
        run: |
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
        env:
          SVN_USERNAME: ${{ secrets.svn_username }}
          SVN_PASSWORD: ${{ secrets.svn_password }}
          SVN_URL: ${{ secrets.svn_url }}

      #note -- test will need to be moved with specific name into test log folder
      #this will probably just be done in the testing script
      - name: run-tests
        run: |
          mkdir sillius_soddius
          cd sillius_soddius
          echo 'Tests run successfully!' > test_log.txt
          echo $env:TEST_RESULTS
          echo $(cat test_log.txt) | Out-File -FilePath $env:TEST_RESULTS
          env:TEST_RESULTS=$(cat test_log.txt)
          cd ..
      - name: check-value
        run: echo $env:TEST_RESULTS

      #clean up
      - uses: JesseTG/rm@v1.0.3
        with:
          path: /svn-repo
      - run: dir
      - uses: actions/checkout@v3

      #ideally we're able to get the version for the revision to add to the comment
      - name: push-log
        run: |
          dir
          cd test_logs
          dir
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          echo test_log.txt > $env:TEST_RESULTS 
          git add .
          git commit -m "Automated Testing for Revision"
          git push

