name: Run end to end tests
run-name: Run more expensive tests that would take too long to run before commits
permissions:
  contents: write
on: 
  repository_dispatch:
    types: end2end
  #push:
  #  branches:
  #    - "*"

jobs:
  run_tests:
    runs-on:  windows-latest
    steps:
      - name: checkout-svn
        run: |
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
        env:
          SVN_USERNAME: ${{ secrets.svn_username }}
          SVN_PASSWORD: ${{ secrets.svn_password }}
          SVN_URL: ${{ secrets.svn_url }}

      - name: run-tests
        run: |
          echo 'End to end tests run successfully!' > test_log.txt
          echo "TEST_OUTPUT=$(cat test_log.txt)" | Out-File -FilePath $env:GITHUB_ENV

      #clean up and check out
      - uses: JesseTG/rm@v1.0.3
        with:
          path: /svn-repo
      - uses: actions/checkout@v3

      #TODO -- add version for the revision to add to the commit message
      #create the log and then push change to commit
      - name: push-log
        run: |
          echo "${{ env.TEST_OUTPUT }}" > test_log.txt
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "Automated Testing for Revision"
          git push

