name: Run end to end tests
run-name: Run more expensive tests that would take too long to run before commits
on: [push]
  #repository_dispatch:
  #  types: end2end

jobs:
  run_tests:
    runs-on:  windows-latest
    steps:
      - name: checkout-svn
        run: |
          cd ..
          svn checkout --username $env:SVN_USERNAME --password $env:SVN_PASSWORD $env:SVN_URL svn-repo
        env:
          SVN_USERNAME: ${{ secrets.svn_username }}
          SVN_PASSWORD: ${{ secrets.svn_password }}
          SVN_URL: ${{ secrets.svn_url }}

      #note -- test will need to be moved with specific name into test log folder
      #this will probably just be done in the testing script
      - name: run-tests
        run: |
          mkdir test_logs
          cd test_logs
          echo 'Tests run successfully!' > test_log.txt
          cd ..
          rmdir svn-repo -r
          dir

      - uses: actions/checkout@v3

      #ideally we're able to get the version for the revision to add to the comment
      - name: push-log
        run: |
          git add .
          git commit -m "Automated Testing for Revision"
          git push

