name: Run end to end tests
run-name: Run end to end tests
permissions:
  contents: write
on: 
  repository_dispatch:
    types: 'end2end'

jobs:
  run_tests:
    runs-on:  windows-latest
    steps:
      - name: checkout-git
        uses: actions/checkout@v3

      - name: pull-svn
        uses: justinli00/leviathan/.github/actions/pull-svn.yaml@main

      - name: run-tests
        run: |
          echo 'End to end tests run successfully!' > test_log.txt
          echo "TEST_OUTPUT=$(cat test_log.txt)" | Out-File -FilePath $env:GITHUB_ENV

      #TODO -- add version for the revision to add to the commit message
      #create the log and then push change to commit
      - name: push-log
        run: |
          cd test_logs
          echo "${{ env.TEST_OUTPUT }}" > test_log.txt
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "Automated Testing for Revision"
          git push

